### ISSUE TITLE
File permissions setting to correct user

### ISSUE THREAD

**Issue by Pancax** [amordahl/ECSTATIC#5]
Only the top level results/ folder is set to correct user. Prob need to chown recursively from that folder.

**Comment by amordahl** [comment]
I actually ended up removing this feature yesterday, because this is a lot more difficult than it seems. I think for now, the best approach we have is that if you, as a user, need to change the permissions of the results files, you should start a new Docker container and change the permissions manually in the container.

**Comment by amordahl** [comment]
For anybody else struggling with this issue, we have solved it by using Docker namespaces or rootless Docker.
